

name: Node.js CI/CD


on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v3
      
      # Step 2: Setup Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Step 3: Install dependencies
      - run: npm ci
      
      # Step 4: Set up environment variables
      - run: |
          touch .env
          echo "${{ secrets.PROD_ENV_FILE }}" > .env

      # Step 5: Restart application with PM2
      - name: Restart BackendAPI
        run: |
          pm2 describe BackendAPI && pm2 restart BackendAPI || echo "BackendAPI not running, skipping restart"
